globals
    // User-defined
location udg_TargetLoc= null
integer udg_Skill_FeralImpact= 0
integer udg_Skill_Bonebreaker= 0
integer udg_Skill_BattleFury= 0
integer udg_Skill_BattleFurrySpeed= 0
integer udg_Skill_Tornado= 0
real udg_g= 0
real udg_FI_DefaultHeight= 0
string udg_FI_EffectA
string udg_FI_EffectB
string udg_FI_Sound
integer udg_BF_DefautInterval= 0
real udg_Shake= 0
integer udg_KB_Max= 0
integer udg_kb= 0
location udg_point= null
unit array udg_KB_Unit
location udg_point2= null
real array udg_KB_Speed
real array udg_KB_Angle
real array udg_KB_Dist
real array udg_KB_MaxDist
integer udg_FI_Max= 0
integer udg_fi= 0
real udg_tmpDiffHeight= 0
real udg_tmpTargetZ= 0
real udg_tmpCasterZ= 0
real udg_tmpHeight= 0
real udg_tmpDistance= 0
unit array udg_FI_Hero
real array udg_FI_z
real array udg_FI_Angle
real array udg_FI_Vz
real array udg_FI_Height
real udg_tmpTime= 0
real array udg_FI_Vp
real array udg_FI_AnimSpeed
sound udg_tmpSound= null
real udg_real2= 0
real udg_real= 0
real udg_FI_FallHeight= 0
group udg_group= null
integer udg_BF_Max= 0
integer udg_bf= 0
unit array udg_BF_Hero
effect array udg_BF_SpecEffect1
effect array udg_BF_SpecEffect2
integer array udg_BF_Time
integer udg_integer= 0
integer udg_TO_Max= 0
unit array udg_TO_Hero
real array udg_TO_Duration
integer udg_to= 0
integer udg_UM_CustomInteger= 0
real array udg_UM_CoreX
real array udg_UM_CoreY
real array udg_UM_Map
real array udg_UM_MaxDistance
effect array udg_UM_MainModelHandler
effect array udg_UM_MatterModelHandler
unit udg_UM_CustomUnit= null
unit array udg_UM_Main
real array udg_UM_MainAngle
real array udg_UM_MatterReturnAngle
integer udg_UM_Ability= 0
integer udg_UM_DummyType= 0
integer udg_UM_AbilityMaxLevel= 0
real array udg_UM_Radius
real array udg_UM_ExplosionRadius
boolean udg_UM_DestroyTrees= false
attacktype udg_UM_AttackType= null
damagetype udg_UM_DamageType= null
real udg_UM_LoopInterval= 0
string array udg_UM_Effect
string array udg_UM_EffectAttach
real array udg_UM_MainSize
real array udg_UM_MainHeight
real array udg_UM_MainSpeed
real udg_UM_MainCreationRange= 0
integer array udg_UM_MatterAmount
real array udg_UM_MatterSize
real array udg_UM_MatterHeight
boolean udg_UM_MatterRotation= false
real array udg_UM_MatterRotationAngleSpeed
real array udg_UM_RevolveDuration
integer udg_UM_MatterMinimumEffect= 0
integer udg_UM_MatterMaximumEffect= 0
string array udg_UM_MatterLightningEffect
integer udg_UM_MatterMinimumLightning= 0
integer udg_UM_MatterMaximumLightning= 0
real array udg_UM_MatterLightningWidth
real array udg_UM_MatterLightningDamage
real array udg_UM_MatterReturnTime
integer udg_UM_MotionEffectChance= 0
boolean udg_UM_MatterCollideExplosion= false
boolean udg_UM_ExplosionOrbsModelSpecific= false
integer array udg_UM_ExplosionOrbsAmount
real array udg_UM_ExplosionOrbsSize
real array udg_UM_ExplosionOrbsMinHeight
real array udg_UM_ExplosionOrbsMaxHeight
real array udg_UM_ExplosionOrbsSpeed
real array udg_UM_ExplosionOrbsCollision
real array udg_UM_ExplosionOrbsDamage
real array udg_UM_ExplosionRadiusDamage
integer udg_UM_ExplosionOrbsArcChance= 0
real array udg_UM_ExplosionOrbsArc
integer udg_UM_EffectsAmount= 0
real array udg_UM_CustomReal
real array udg_UM_CustomReal2
real array udg_UM_CustomReal3
real array udg_UM_CustomReal4
real array udg_UM_CustomReal5
real array udg_UM_CustomReal6
unit array udg_UM_Caster
integer udg_UM_ID= 0
player array udg_UM_CasterPlayer
integer array udg_UM_Level
unit udg_UM_Unit= null
real array udg_UM_CurrentDistance
integer array udg_UM_Phase
group udg_UM_Group= null
real array udg_UM_MatterAngle
integer udg_UM_CustomID= 0
real udg_LH_DurationSet= 0
string udg_LH_LightningNameSet
unit udg_LH_UnitSourceSet= null
unit udg_LH_UnitTargetSet= null
real array udg_UM_MatterRevolveAngle
real array udg_UM_RevolveDurationCounter
real array udg_UM_MatterReturnTimeCounter
real array udg_UM_MatterCurrentDistance
boolean array udg_UM_CustomBoolean
real udg_LSE_Width= 0
trigger udg_LSE_Trigger_GetUnits= null
group udg_LSE_Group= null
unit udg_UM_PickedUnit= null
unit udg_KB3D_Unit= null
real udg_KB3D_Range= 0
real udg_KB3D_Speed= 0
real udg_KB3D_Angle= 0
boolean udg_KB3D_D_ENEMY= false
string udg_KB3D_EndFx
real udg_KB3D_AoEEndDamage= 0
boolean udg_KB3D_EndwhenDead= false
boolean udg_KB3D_KillatEnd= false
real udg_KB3D_AoE= 0
real udg_KB3D_Arc= 0
attacktype udg_KB3D_AttackType= null
damagetype udg_KB3D_DamageType= null
unit udg_KB3D_Damager= null
boolean udg_KB3D_DestroyTree= false
boolean udg_KB3D_DisableUnit= false
boolean udg_KB3D_FaceAngle= false
boolean udg_KB3D_iKB= false
boolean udg_KB3D_JumpOverCliff= false
string udg_KB3D_Attach
string udg_KB3D_TrailFx
boolean udg_KB3D_UnpathableStop= false
real udg_KB3D_Zoffset= 0
real udg_M_Radius= 0
real array udg_M_Damage
real udg_M_Denominator= 0
real udg_M_Numerator= 0
real udg_M_Loops= 0
real udg_M_SpeedBase= 0
real udg_M_Speed= 0
real udg_M_AnglePlus= 0
string udg_M_SuckSFX
real array udg_M_Duration
string udg_M_TornadoSFX
unit udg_M_Caster= null
location udg_M_TargetLoc= null
integer udg_M_Levels= 0
unit udg_M_Tornado= null
location udg_M_SFXOffset= null
integer udg_M_THandle= 0
hashtable udg_M_Hash= null
group udg_M_TornadoGroup= null
unit udg_M_Picked= null
integer udg_M_PickedHandle= 0
location udg_M_PickedLoc= null
group udg_M_VictimGroup= null
unit udg_M_PickedV= null
location udg_M_PickedVLoc= null
real udg_M_DistanceBase= 0
real udg_M_DamageLoop= 0
real udg_M_Angle= 0
location udg_M_SuckOffset= null
integer udg_SD_Ability= 0
integer udg_SD_EvasionDummy= 0
integer udg_SD_Shadow= 0
real udg_SD_Distance= 0
real udg_SD_Speed= 0
real array udg_SD_Damage
damagetype udg_SD_DamageType= null
attacktype udg_SD_AttackType= null
string udg_SD_Animation
real udg_SD_AnimSpeed= 0
real udg_SD_Offset= 0
real udg_SD_Degrees= 0
string udg_SD_SFX1
string udg_SD_SFX2
integer udg_SD_IndexSize= 0
integer array udg_SD_Index
integer udg_SD_MaxIndexSize= 0
integer udg_SD_TempInt= 0
unit array udg_SD_Caster
unit array udg_SD_Target
location array udg_SD_Loc
unit array udg_SD_Shadows
integer array udg_SD_LOA
integer udg_SD_Looper= 0
real array udg_SD_Angle
hashtable udg_hashtable= null
boolean udg_manaburn= false
real array udg_damage
real array udg_areaofeffect
string udg_unitsfx
string udg_orderid
group udg_stormgroup= null
unit udg_caster= null
boolean udg_boolean= false
integer udg_handle= 0
location udg_point1= null
integer udg_level= 0
unit udg_target= null
lightning udg_light= null
force udg_TempGroup= null
unit udg_Caster= null
unit udg_Target= null
location udg_TempLoc= null
location udg_TempLoc2= null
real udg_TempReal= 0
integer udg_TempInt2= 0
unit udg_TempUnit= null
integer udg_TempInt= 0
integer udg_IAIndex= 0
integer udg_IALastRecycled= 0
integer array udg_IARecycledList
integer udg_IAMax= 0
boolean array udg_IAHas
unit array udg_IACaster
location array udg_IATargetPoint
location array udg_IACasterPoint
real array udg_IAMaxDistance
real array udg_IADistance
real array udg_IADamage
integer udg_IACount= 0
real array udg_IAAngle
unit array udg_IAArrow
integer udg_IAInteger= 0
group array udg_IADMGGroup
location udg_TempLoc3= null
integer udg_ARIndex= 0
integer udg_ARLastRecycled= 0
integer array udg_ARRecycledList
integer udg_ARMax= 0
boolean array udg_ARHas
unit array udg_ARCaster
location array udg_ARTargetPoint
real array udg_ARDelay
integer array udg_ARArrows
integer udg_ARCount= 0
real array udg_ARDamage
group array udg_ARArrowsGroup
integer udg_ARInteger= 0
group array udg_ARArrowsGroup2
integer udg_FAIndex= 0
integer udg_FALastRecycled= 0
integer array udg_FARecycledList
integer udg_FAMax= 0
boolean array udg_FAHas
unit array udg_FACaster
integer udg_FACount= 0
location array udg_FATargetPoint
real array udg_FATimer
real array udg_FADelay
integer udg_FAInteger= 0
hashtable udg_SpellHash= null
integer udg_SF_BouncesNumber= 0
real udg_SF_RangeBetweenBounces= 0
real udg_SF_RangeOfSmallMissiles= 0
integer udg_SF_NumberOfSmallMissiles= 0
real udg_SF_DamageBigMissiles= 0
real udg_SF_DamageSmallMissiles= 0
boolean udg_SF_DestroyTrees= false
unit udg_JDA_Caster= null
location array udg_SF_TempPoint
real udg_JDA_JumpHigh_Distance= 0
boolean udg_JDA_DestroyTrees_Dash= false
location udg_JDA_TargetPoint= null
unit udg_JDA_Unit= null
real udg_JDA_Speed= 0
boolean udg_JDA_SmallFalse_BigTrue= false
integer array udg_JD_Integers
location udg_JD_SmallPoint= null
real array udg_JD_Distances
real array udg_JD_ReachedDistance
real array udg_JD_SpeedUnits
unit array udg_JD_Unit
real array udg_JD_Angle
boolean array udg_JD_TreesDestroy
real array udg_JD_HighSettings
boolean array udg_JD_SmallFalse_BigTrue
unit array udg_JD_Owner
real array udg_JD_DamageBig
real array udg_JD_DamageSmall
integer array udg_JD_BouncesMax
integer array udg_JD_BouncesCur
group udg_JD_Group= null
location array udg_JD_TempPoint
group udg_JD_TempGroup= null
real array udg_JD_RealTimer
integer udg_JD_IntegerAVar= 0
real array udg_JD_JumpHigh
unit udg_GushUnit= null
unit udg_GushTarget= null
location udg_GushPoint= null
unit udg_GushDummy= null
group udg_KrakenGroup= null
integer udg_KrakenCount= 0
integer array udg_KrakenCounterStart
real array udg_KrakenTimeCounter
real array udg_KrakenDamageCount
location udg_AnchorPoint= null
group udg_AnchorGroup= null
unit udg_RavageUnit= null
location udg_RavagePoint= null
unit array udg_RavageDummy
location array udg_RavageDummyPoint
group udg_RavageGroup= null
force udg_RavagePlayer= null
unit udg_RavageTarget= null
location udg_RavageTargetPoint= null
unit udg_RavageStunDummy= null
unit udg_SparkyUnit= null
timerdialog udg_TimeWindow= null
timer udg_Timer= null
real udg_Seconds= 0
integer udg_UDex= 0
integer array udg_UnitIndexLock
integer array udg_UDexPrev
integer array udg_UDexNext
real udg_UnitIndexEvent= 0
unit array udg_UDexUnits
integer udg_UDexRecycle= 0
boolean udg_UnitIndexerEnabled= false
integer udg_UDexWasted= 0
integer udg_UDexGen= 0
integer udg_DamageBlockingAbility= 0
integer udg_SpellDamageAbility= 0
integer udg_DamageTypeExplosive= 0
integer udg_DamageTypeCriticalStrike= 0
integer udg_DamageTypeHeal= 0
integer udg_DamageTypeReduced= 0
integer udg_DamageTypeBlocked= 0
integer udg_DmgEvBracers= 0
real udg_DAMAGE_FACTOR_BRACERS= 0
real udg_DAMAGE_FACTOR_ELUNES= 0
real udg_DAMAGE_FACTOR_ETHEREAL= 0
integer udg_DamageEventAOE= 0
integer udg_DamageEventLevel= 0
real udg_AfterDamageEvent= 0
real udg_DamageEvent= 0
real udg_AOEDamageEvent= 0
real udg_DamageModifierEvent= 0
trigger udg_ClearDamageEvent= null
real udg_DamageEventAmount= 0
real udg_DamageEventPrevAmt= 0
boolean udg_DamageEventOverride= false
boolean udg_NextDamageOverride= false
unit udg_DamageEventSource= null
unit udg_DamageEventTarget= null
trigger udg_DamageEventTrigger= null
trigger udg_DmgEvTrig= null
integer udg_DamageEventType= 0
integer array udg_LastDmgPrevType
integer udg_NextDamageType= 0
integer udg_DamageEventsWasted= 0
integer udg_DmgEvRecursionN= 0
boolean udg_DmgEvRunning= false
boolean udg_DmgEvStarted= false
boolean udg_IsDamageSpell= false
boolean array udg_LastDmgWasSpell
real udg_LastDamageHP= 0
timer udg_DmgEvTimer= null
real array udg_LastDmgPrevAmount
real array udg_LastDmgValue
unit array udg_LastDmgSource
unit array udg_LastDmgTarget
boolean array udg_HideDamageFrom
boolean array udg_UnitDamageRegistered
unit udg_EnhancedDamageTarget= null
group udg_DamageEventAOEGroup= null
real array udg_AMSAmount
real udg_DmgEvMana= 0
integer udg_DmgEvMSlvl= 0
real udg_DmgEvManaMult= 0
integer array udg_UMovNext
integer array udg_UMovPrev
boolean array udg_UnitMoving
real array udg_UnitMovingX
real udg_TempX= 0
real array udg_UnitMovingY
real udg_TempY= 0
real udg_UnitMovingEvent= 0
string udg_AOEString
integer udg_gold= 0
integer udg_Lumber= 0
force udg_tempgroup= null
group udg_Tmp_UnitGroup= null
location udg_Tmp_Loc= null
sound array udg_Arthas1
location udg_rainpoint= null
force udg_playercountgroup= null
force udg_damagegroupvar= null
location udg_Pointofdamage= null
string udg_string
unit udg_Building= null
location udg_pointmap= null
group udg_EvasionGroup= null
group udg_NotEvasionGroup= null
integer udg_EvasionLevel= 0
group udg_worker= null
unit udg_Goldmine= null
location udg_Targetspell= null
real udg_Delayed_Duration= 0
effect udg_Delayed_SFX= null
integer udg_VengeanceAura= 0
group udg_VengeanceGroup= null
group udg_NotVengeanceGroup= null
integer udg_Piercechance= 0
location udg_TempPiercePoint= null
location udg_Arsonnew= null
group udg_RecruitGroup= null
integer udg_RecruitLevel= 0
group udg_NotRecruit= null
location udg_Zombietarget= null
real array udg_DamageTaken
integer array udg_DamageTotalWorkfroce
unit udg_ShieldUnit= null
integer udg_Randomweather= 0
weathereffect udg_Weather_effect= null
integer udg_Randomweather2= 0
hashtable udg_WeatherHash= null
integer array udg_Weather
group udg_Satanicgroup= null
group udg_PedGroup= null
group udg_TentacleGroup= null
group udg_TentacleGroup3= null
group udg_TentacleGroup2= null
hashtable udg_HASHTENTACLE= null
integer udg_Tentacleinteger= 0
integer udg_Tentacleinteger2= 0
location array udg_Tentaclepoint
real array udg_TentacleReal
unit array udg_TentacleTemp
location udg_RecruitPoint= null
group array udg_RecruitUndyingGroup
unit udg_Watcherdamaged= null
integer udg_FalsePromise_Ability= 0
integer array udg_FalsePromise_AbilityLvl
integer udg_FalsePromise_AbiLvl= 0
integer udg_FalsePromise_Buff= 0
real array udg_FalsePromise_Counter
real array udg_FalsePromise_CounterDamage
real array udg_FalsePromise_CounterHeal
real array udg_FalsePromise_Damage
unit array udg_FalsePromise_DamageUnit
real array udg_FalsePromise_Duration
real udg_FalsePromise_Event= 0
hashtable udg_FalsePromise_Hash= null
real array udg_FalsePromise_HealMultiplier
real array udg_FalsePromise_HitPoints
integer udg_FalsePromise_LoopInt= 0
integer udg_FalsePromise_MaxIndex= 0
integer array udg_FalsePromise_NodeNext
integer array udg_FalsePromise_NodePrev
real udg_FalsePromise_PeriodicTimer= 0
integer udg_FalsePromise_RecycledSize= 0
integer array udg_FalsePromise_RecycledStack
string udg_FalsePromise_SFXCredit
string udg_FalsePromise_SFXDamage
string udg_FalsePromise_SFXCredit_AP
string udg_FalsePromise_SFXDamage_AP
string udg_FalsePromise_SFXHeal
string udg_FalsePromise_SFXHeal_AP
string udg_FalsePromise_SFXTarget
string udg_FalsePromise_SFXTarget_AP
integer udg_FalsePromise_Spell_ID= 0
integer udg_FalsePromise_SpellCount= 0
integer array udg_FalsePromise_SpellNode
unit array udg_FalsePromise_Target
effect array udg_FalsePromise_TargetSFX
integer udg_FalsePromise_TempInt= 0
real udg_FalsePromise_TempReal= 0
unit udg_FalsePromise_Unit= null
integer udg_FalsePromise_Unit_ID= 0